UniversityManagementWebApp/UniversityManagementWebApp/Models/CourseStatics.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementWebApp.Models
{
    public class CourseStatics
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Semester { get; set; }
        public string AssignTo { get; set; }
    }
}

UniversityManagementWebApp/UniversityManagementWebApp/Controllers/CourseStaticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementWebApp.Manager;
using UniversityManagementWebApp.Models;

namespace UniversityManagementWebApp.Controllers
{
    public class CourseStaticsController : Controller
    {
        //
        // GET: /CourseStatics/
        private DepartmentManager departmentManager;
        private CourseStaticsManager courseStaticsManager;

        public CourseStaticsController()
        {
            departmentManager = new DepartmentManager();
            courseStaticsManager = new CourseStaticsManager();
        }

        [HttpGet]
        public ActionResult Statics()
        {
            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            return View();
        }
        public JsonResult GetCourseStaticById(int deptId)
        {
            List<CourseStatics> courseStaticses = courseStaticsManager.GetCourseStaticsesById(deptId);
            return Json(courseStaticses);
        }
    }
}

UniversityManagementWebApp/UniversityManagementWebApp/Views/CourseStatics/Statics.cshtml
@using UniversityManagementWebApp.Models
@{
    ViewBag.Title = "Statics";
    Layout = "../Shared/view1.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <style>

        table,th,td{
            border: 1px solid black;
        }

    </style>
    @section style
{
        <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
        <link href="~/Content/DataTables/css/dataTables.jqueryui.min.css" rel="stylesheet" />
        <link href="~/Content/DataTables/css/fixedColumns.jqueryui.min.css" rel="stylesheet" />
        <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    }
</head>
<body>
    @using (Html.BeginForm())
    {
        <table>
            <tr>
                <td>
                    @Html.Label("Department")
                </td>
                <td>
                    @Html.DropDownList("Department", new SelectList(ViewBag.Departments,"Value","Text"))
                </td>
            </tr>
        </table>
        <br />
        <h4>Course Information</h4>
    <table id="dataTable" class="table table-bordered table-responsive table-hover">

        <thead>

            <tr>
                <td>Code</td>
                <td>Name/Title</td>
                <td>Semester</td>
                <td>Assigned To</td>
            </tr>

        </thead>

        <tbody id="courseDetails"></tbody>
    </table>
    }

    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
<script>

    $(document).ready(function () {
        
        $("#dataTable").hide();
        $("#Department").change(function () {

            $("#dataTable").hide();
            var departmentId = $("#Department").val();
            $("#courseDetails").empty();

            var json = { deptId: departmentId };


            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseStaticById", "CourseStatics")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $("#dataTable").show();

                    $.each(data, function (key, value) {
                        $("#courseDetails").append('<tr><td>' + value.Code + '</td>   <td>' + value.Name + '</td>   <td>' + value.Semester +
                                                    '</td> <td>' + value.AssignTo + '</td> </tr>');
                    });
                }
            });

        });
    });
</script>



</body>
</html>