UniversityManagementWebApp/UniversityManagementWebApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementWebApp.Manager;
using UniversityManagementWebApp.Models;

namespace UniversityManagementWebApp.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/

        private CourseManager courseManager;
        private SemesterManager semesterManager;
        private DepartmentManager departmentManager;

        public CourseController()
        {
            courseManager = new CourseManager();
            semesterManager = new SemesterManager();
            departmentManager = new DepartmentManager();
        }

        [HttpGet]
        public ActionResult Save()
        {
            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            ViewBag.Semesters = semesterManager.GetSemesterForDropdown();
            return View();
        }

        [HttpPost]
        public ActionResult Save(Course course)
        {
            if (ModelState.IsValid)
            {
                string message = courseManager.Save(course);
                ViewBag.Message = message;
                if (message == "Save Successful")
                {
                    ModelState.Clear();
                }
            }

            else
            {
                ViewBag.Message = "ModelState Is not valid";
            }

            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            ViewBag.Semesters = semesterManager.GetSemesterForDropdown();
            
            return View();
        }
	}
}

UniversityManagementWebApp/UniversityManagementWebApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementWebApp.Manager;
using UniversityManagementWebApp.Models;

namespace UniversityManagementWebApp.Controllers
{
    public class DepartmentController : Controller
    {
        private DepartmentManager departmentManager;

        public DepartmentController()
        {
            departmentManager = new DepartmentManager();
        }
    //    public ActionResult Index()
    //    {
    //        return View();
    //    }

        [HttpGet]
        public ActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(Department department)
        {
            if (ModelState.IsValid)
            {
                string message = departmentManager.Save(department);
                ViewBag.Message = message;
                if (message == "Save Successful")
                {
                    ModelState.Clear();
                }
            }
            else
            {
                ViewBag.Message = "ModelState is ot valid";
            }
            
            return View();
        }

        public ActionResult ShowDepartment()
        {
            List<Department> departmentList = departmentManager.GetAllDepartment();
            return View(departmentList);
        }
	}
}

UniversityManagementWebApp/UniversityManagementWebApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementWebApp.Manager;
using UniversityManagementWebApp.Models;

namespace UniversityManagementWebApp.Controllers
{
    public class TeacherController : Controller
    {
        //
        // GET: /Teacher/
        private DesignationManager designationManager;
        private TeacherManager teacherManager;
        private DepartmentManager departmentManager;

        public TeacherController()
        {
            departmentManager = new DepartmentManager();
            teacherManager = new TeacherManager();
            designationManager = new DesignationManager();
        }
        [HttpGet]
        public ActionResult Save()
        {
            ViewBag.Designations = designationManager.GetDesignationForDropdown();
            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            return View();
        }

        [HttpPost]

        public ActionResult Save(Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                string message = teacherManager.Save(teacher);
                ViewBag.Message = message;
                if (message == "Save Successful")
                {
                    ModelState.Clear();
                }
            }
            else
            {
                ViewBag.Message = "ModelState is invalid";
            }

            ViewBag.Designations = designationManager.GetDesignationForDropdown();
            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            
            return View();
        }
	}
}

UniversityManagementWebApp/UniversityManagementWebApp/Views/Shared/NavBar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=0.00">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("style", false)
    <style>
        body {
            font-family: "Lato", sans-serif;
            transition: background-color .5s;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 25px;
                color: #818181;
                display: block;
                transition: 0.3s;
            }

                .sidenav a:hover {
                    color: #f1f1f1;
                }

            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding: 16px;
        }
    </style>
</head>
<body>

    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">Menu Bar &times;</a>
        <ul style="font-size:5%">
            <li style="font-size: small;"><h4 style="background-color: red;"></h4>@Html.ActionLink("Home", "Index", "Home")</h1></li>
            <li></li>
            <li>@Html.ActionLink("Save Department", "Save", "Department")</li>
            <li>@Html.ActionLink("View All Department", "ShowDepartment", "Department")</li>
            <li>@Html.ActionLink("Save Course", "Save", "Course")</li>
            <li>@Html.ActionLink("Save Teacher", "Save", "Teacher")</li>
            <li>@Html.ActionLink("Course Assign To Teacher", "Assign", "AssignCourseToTeacher")</li>
            <li>@Html.ActionLink("View Course Statics", "Statics", "CourseStatics")</li>
            <li>@Html.ActionLink("Register Student", "Register", "RegisterStudent")</li>
            <li>@Html.ActionLink("Allocate Class Room", "ClassRoom", "AllocateClassRoom")</li>
            <li>@Html.ActionLink("View Class & Room Allocation Information", "ClassRoomScedule", "ClassRoomSceduleAllocation")</li>
            <li>@Html.ActionLink("Enroll In A course", "EnrollInACourse", "EnrollCourseToStudeent")</li>
            <li>@Html.ActionLink("Save Student Result", "SaveStudentResult", "SaveStudentsResult")</li>
            <li>@Html.ActionLink("View Student Result", "Result", "StudentResult")</li>
            <li>@Html.ActionLink("Unassign All Courses", "UnassignCourses", "UnassignAllCourses")</li>
            <li>@Html.ActionLink("Unallocate All Rooms", "UnallocateRooms", "UnallocateAllRooms")</li>
        </ul>
    </div>



    <div class="container body-content">

        <div id="main" align="left">

            <div style="float:left"><span style="font-size: 30px; cursor: pointer" onclick="openNav()">&#9776;</span></div>
            <div align="center" style="float:left">
                @RenderBody()
            </div>
            <hr />
            <footer></footer>
        </div>
    </div>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "350px";
            document.getElementById("main").style.marginLeft = "250px";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            document.body.style.backgroundColor = "white";
        }
    </script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

UniversityManagementWebApp/UniversityManagementWebApp/Views/Shared/_LayoutDesign.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=0.00">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Styles/style.css" rel="stylesheet" />
    <link href="~/Styles/style_uwp.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("style", false)
</head>
<body class="home blog livecss">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="False">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("University Management", "Index", "Home", null, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Save Department", "Save", "Department")</li>
                            <li>@Html.ActionLink("View All Department", "ShowDepartment", "Department")</li>
                            <li>@Html.ActionLink("Save Course", "Save", "Course")</li>
                            <li>@Html.ActionLink("Course Assign To Teacher", "Assign", "AssignCourseToTeacher")</li>
                            <li>@Html.ActionLink("View Course Statics", "Statics", "CourseStatics")</li>
                            <li>@Html.ActionLink("Register Student", "Register", "RegisterStudent")</li>
                            <li>@Html.ActionLink("Allocate Class Room", "ClassRoom", "AllocateClassRoom")</li>
                            <li>@Html.ActionLink("View Class & Room Allocation Information", "ClassRoomScedule", "ClassRoomSceduleAllocation")</li>
                            <li>@Html.ActionLink("Enroll In A course", "EnrollInACourse", "EnrollCourseToStudeent")</li>
                            <li>@Html.ActionLink("Save Student Result", "SaveStudentResult", "SaveStudentsResult")</li>
                            <li>@Html.ActionLink("View Student Result", "Result", "StudentResult")</li>
                            <li>@Html.ActionLink("Unassign All Courses", "UnassignCourses", "UnassignAllCourses")</li>
                            <li>@Html.ActionLink("Unallocate All Rooms", "UnallocateRooms", "UnallocateAllRooms")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>












    @*<div id="header-panel">
                    <div class="page">
                        <div id="header">
                            <div class="header-top">
                                <div class="language">
                                    <ul class="lang-list"></ul><!--lang-list end-->
                                </div><!--language end-->
                                <div class="loginrss">
                                    <ul class="logrss-list">
                                        <li><a href="http://www.iiuc.ac.bd/">IIUC Home</a></li>
                                    </ul>
                                </div><!--loginrss end-->
                                <div class="clear"></div>
                            </div><!--header-top end-->
                            <div class="clear"></div>
                            <div class="header-main">
                                <a class="logo" href="#"></a>
                                <div id="ms-bg">
                                    <div id="main-menu">
                                        <div class="menu-header">

                                            <ul><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='#' class="sf-with-ul">Home</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='Preregistration.php' class="sf-with-ul">Preregistration</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='schedule.php' class="sf-with-ul">Confirm Pre-Registration</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='Billing.php' class="sf-with-ul">Billing</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='advisingBill.php' class="sf-with-ul">Advising Bill</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='Status.php' class="sf-with-ul">Result</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='profile.php' class="sf-with-ul">Profile</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='terindex.php' class="sf-with-ul">TER Submission</a></li><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='index.php?logout=1' class="sf-with-ul">Logout</a></li></ul>
                                        </div>
                                    </div><!--main-menu end-->
                                    <div id="search">
                                    </div><!--search end-->
                                    <div class="clear"></div>
                                </div><!--ms-bg end-->
                            </div><!--header-main end-->
                        </div><!--header end-->
                    </div><!--page end-->
                </div><!--header-panel-->
                <div class="page">
                    <div class="clear"></div>
                    <div id="Content-fullwidth">
                        <div id="uwp-cleMain">
                            <div id="uwp-user">&nbsp;You are logged in as: <b>C161003</b> (<a href='index.php?logout=1'>log out</a>)</div>
                            <div id="uwp-filter-info"><p class='uwp-student-info-header'>&nbsp;&nbsp;&nbsp; </p><p class='uwp-student-info'><b>Semester: </b>183 (<i>Autumn 2018</i>) <b>Student: </b>C161003 Md. Shahadat Hossain  <br /><b>Adviser: </b>Md. Ziaur Rahman</p></div>
                            <div id="rest">
                                <div class="uwp-prop"></div>

                                <div id="msgBar"></div>
                                <div id="cleContent">
                                    <table class="uwp-noborder">
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../Department/Save">Save Department</a></td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../Department/ShowDepartment">View All Departments</a></td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../Course/Save">Save Course</a></td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../Teacher/Save">Save Teacher</a></td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../AssignCourseToTeacher/Assign">Course Assign To Teacher</a> </td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../CourseStatics/Statics">View Course Statics</a></td>
                                        </tr>

                                        <tr>
                                            <td class="uwp-menu-item"><a href="../RegisterStudent/Register">Register Student</a> </td>
                                        </tr>

                                        <tr>
                                            <td class="uwp-menu-item"><a href="../AllocateClassRoom/ClassRoom">Allocate ClassRooms</a></td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../ClassRoomSceduleAllocation/ClassRoomScedule">View Class & Room Allocation Information</a></td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../EnrollCourseToStudeent/EnrollInACourse">Enroll In A Course</a></td>
                                        </tr>
                                        <tr>
                                            <td class="uwp-menu-item"><a href="../SaveStudentsResult/SaveStudentResult">Save Student Result</a></td>

                                        </tr>
                                        <tr>

                                            <td class="uwp-menu-item"><a href="../StudentResult/Result">View Result</a></td>
                                        </tr>
                                        <tr>

                                            <td class="uwp-menu-item"><a href="../UnassignAllCourses/UnassignCourses">Unassign All Courses</a></td>
                                        </tr>
                                        <tr>

                                            <td class="uwp-menu-item"<a href="../UnallocateAllRooms/UnallocateRooms">Unallocate All Class Rooms</a>></td>
                                        </tr>
                                    </table>

                                </div>
                            </div>
                        </div><div class="clear"></div>
                    </div>
                    <!--content end-->
                    <div id="footer">
                        <div class="box986-top">
                            <div class="box986-bottom">
                                <div class="box986-mid">
                                    <div class="footer-widget-section">
                                        <div class="clear"></div>
                                    </div><!--footer-widget end-->
                                </div><!--box-487-mid end-->
                                <div class="copyright-social">
                                    <div class="copyright">
                                        <p>
                                            Copyright © 2016
                                            <a href="./International Islamic University Chittagong_files/International Islamic University Chittagong.htm">IIUC</a>
                                            | All Rights Reserved
                                        </p>
                                    </div><!--copyright end-->
                                    <div class="counter">
                                        <div class="footer-widget-5">
                                            <div class="textwidget">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="social">
                                <p>
                                    System developed by:
                                    <a href="http://www.vpcsbd.com">ValuePLUS Computer Systems Ltd.</a>
                                </p>
                            </div><!--social end-->
                            <div class="clear"></div>
                        </div><!--copyright-social end-->
                    </div><!--box-487-bottom end-->
                </div><!--box-487-top end-->
            </div><!--footer end-->
            <!--stats_footer_test-->
        </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>