UniversityManagementWebApp/UniversityManagementWebApp/Models/AssignCourseToTeacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementWebApp.Models
{
    public class AssignCourseToTeacher
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please select a department")]
        [Display(Name = "Department")]
        public int DepartmentId { get; set; }

        [Required(ErrorMessage = "Please select a teacher")]
        [Display(Name = "Teacher")]
        public int TeacherId { get; set; }

        [Display(Name = "Credit To Be Taken")]
        public decimal CreditToBeTaken { get; set; }

        [Display(Name = "Remaining Credit")]
        public decimal RemainingCredit { get; set; }

        [Required(ErrorMessage = "Please select a course")]
        [Display(Name = "Course")]
        public int CourseId { get; set; }

        [Display(Name = "Name")]
        public string CourseName { get; set; }

        [Display(Name = "Credit")]
        public decimal CourseCredit { get; set; }
    }
}

UniversityManagementWebApp/UniversityManagementWebApp/Controllers/AssignCourseToTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementWebApp.Manager;
using UniversityManagementWebApp.Models;

namespace UniversityManagementWebApp.Controllers
{
    public class AssignCourseToTeacherController : Controller
    {
        private AssignCourseToTeacherManager assignCourseToTeacherManager;
        private DepartmentManager departmentManager;
        private TeacherManager teacherManager;
        private CourseManager courseManager;

        public AssignCourseToTeacherController()
        {
            assignCourseToTeacherManager = new AssignCourseToTeacherManager();
            departmentManager = new DepartmentManager();
            teacherManager = new TeacherManager();
            courseManager = new CourseManager();
        }
        
        [HttpGet]
        public ActionResult Assign()
        {
            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            ViewBag.teacher = new List<SelectListItem>(){
                new SelectListItem(){
                    Text = "--Select--",Value = "", Selected = true
                }
            };
            return View();
        }

        [HttpPost]
        public ActionResult Assign(AssignCourseToTeacher aCourseToTeacher)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Message = assignCourseToTeacherManager.Assign(aCourseToTeacher);
                if (ViewBag.Message == "The selected course is already assigned") ModelState.Clear();
                else if (ViewBag.Message != null)
                {
                    string message =
                    teacherManager.UpdateTeacherRemainingCredit(aCourseToTeacher.TeacherId, aCourseToTeacher.RemainingCredit -
                                                                aCourseToTeacher.CourseCredit);
                    if (message == "Update successful")
                    {
                        ModelState.Clear();
                    }
                }
            }
            else
            {
                ViewBag.Message = "Please enter valid information";
            }
            
            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            ViewBag.teacher = new List<SelectListItem>(){
                new SelectListItem(){
                    Text = "--Select--",Value = "", Selected = true
                }
            };
            
            return View();
        }

        public JsonResult GetTeachersByDepartmentId(int departmentId)
        {
            List<SelectListItem> teachers = teacherManager.GetTeachersByDepartmentId(departmentId);

            return Json(teachers);
        }

        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            List<SelectListItem> courses = courseManager.GetCoursesByDepartmentId(departmentId);

            return Json(courses);
        }

        public JsonResult GetTeacherDetailsByTeacherId(int teacherId)
        {
            Teacher teacher =  teacherManager.GetTeacherDetailsByTeacherId(teacherId);
            List<Teacher> teachers = new List<Teacher>();
            teachers.Add(teacher);
            return Json(teachers);
        }

        public JsonResult GetCourseDetailsByCourseId(int courseId)
        {
            Course course = courseManager.GetCourseDetailsByCourseId(courseId);
            List<Course> courses = new List<Course>();
            courses.Add(course);
            return Json(courses);
        }
	}
}

UniversityManagementWebApp/UniversityManagementWebApp/Views/AssignCourseToTeacher/Assign.cshtml
@using UniversityManagementWebApp.Models
@model AssignCourseToTeacher
@{
    ViewBag.Title = "Assign";
    Layout = "../Shared/view1.cshtml";
    // Layout = null;
}

<body>


    @using (Html.BeginForm())
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(x => x.DepartmentId)
                </td>
                <td>
                    @Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "Value", "Text"))
                    @Html.ValidationMessageFor(x => x.DepartmentId)
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(x => x.TeacherId)
                </td>
                <td>
                    @Html.DropDownListFor(x => x.TeacherId, new SelectList(ViewBag.teacher, "Value", "Text"))
                    @Html.ValidationMessageFor(x => x.TeacherId)
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(x => x.CreditToBeTaken)
                </td>
                <td>
                    @Html.TextBoxFor(x => x.CreditToBeTaken, new { @readonly = "readonly" })
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(x => x.RemainingCredit)
                </td>
                <td>
                    @Html.TextBoxFor(x => x.RemainingCredit, new { @readonly = "readonly" })
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(x => x.CourseId)
                </td>
                <td>
                    @Html.DropDownListFor(x => x.CourseId, new SelectList(new List<SelectListItem>
                    {
                        new SelectListItem() {Text = "---Select---", Value = ""}
                    }, "Value", "Text"))
                    @Html.ValidationMessageFor(x => x.CourseId)
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(x => x.CourseName)
                </td>
                <td>
                    @Html.TextBoxFor(x => x.CourseName, new { @readonly = "readonly" })
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(x => x.CourseCredit)
                </td>
                <td>
                    @Html.TextBoxFor(x => x.CourseCredit, new { @readonly = "readonly" })
                </td>
            </tr>

            <tr>
                <td></td>
                <td>
                    <input id="Assign" name="Assign" value="Assign" type="submit" />
                </td>
            </tr>

        </table>

        if (@ViewBag.Message != null)
        {
            <h3>@ViewBag.Message</h3>
        }
    }

    @section scripts
    {
        <script src="~/Scripts/jquery-3.5.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        <script>
            $(document).ready(function () {

                $("#DepartmentId").change(function () {

                    var json = { departmentId: $("#DepartmentId").val() };

                    $("#TeacherId").empty();
                    $("#CourseId").empty();

                    $("#CreditToBeTaken").val("");
                    $("#RemainingCredit").val("");


                    $("#CourseName").val("");
                    $("#CourseCredit").val("");

                    $("#TeacherId").append('<option value=""> ---Select---</option>');
                    $("#CourseId").append('<option value=""> ---Select---</option>');



                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetTeachersByDepartmentId", "AssignCourseToTeacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $("#TeacherId").empty();
                            $.each(data, function (key, value) {

                                $("#TeacherId").append('<option value="' + value.Value + '">' + value.Text + '</option>');

                            });

                        }
                    });

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetCoursesByDepartmentId", "AssignCourseToTeacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $("#CourseId").empty();
                            $.each(data, function (key, value) {

                                $("#CourseId").append('<option value="' + value.Value + '">' + value.Text + '</option>');

                            });

                        }
                    });

                });

                $("#TeacherId").change(function () {

                    $("#CreditToBeTaken").val("");
                    $("#RemainingCredit").val("");

                    $("#CourseName").val("");
                    $("#CourseCredit").val("");

                    var json = { teacherId: $("#TeacherId").val() };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetTeacherDetailsByTeacherId", "AssignCourseToTeacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {
                            $.each(data, function (key, value) {
                                $("#CreditToBeTaken").val(value.CreditToBeTaken);
                                $("#RemainingCredit").val(value.RemainingCredit);

                            });

                        }
                    });

                });

                $("#CourseId").change(function () {

                    $("#CourseName").val("");
                    $("#CourseCredit").val("");

                    var json = { courseId: $("#CourseId").val() };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetCourseDetailsByCourseId", "AssignCourseToTeacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {
                            $.each(data, function (key, value) {
                                $("#CourseName").val(value.Name);
                                $("#CourseCredit").val(value.Credit);

                            });

                        }
                    });

                });

                $("#Assign").click(function () {
                    var remaining = Number($("#RemainingCredit").val());
                    var credit = Number($("#CourseCredit").val());
                    console.log(remaining);
                    console.log(credit);
                    if (credit <= remaining) return true;
                    if (credit > remaining) {
                        return confirm('Course credit is more than Remaining Credit . Do you want to proceed?');
                    }
                    return false;
                });
            });
        </script>
    }
</body>