UniversityManagementWebApp/UniversityManagementWebApp/Models/ClassRoomScedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementWebApp.Models
{
    public class ClassRoomScedule
    {
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string Room { get; set; }
        public string Day { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string ClassScheduleInfo { get; set; }
    }
}

UniversityManagementWebApp/UniversityManagementWebApp/Controllers/ClassRoomSceduleAllocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementWebApp.Manager;
using UniversityManagementWebApp.Models;

namespace UniversityManagementWebApp.Controllers
{
    public class ClassRoomSceduleAllocationController : Controller
    {
        //
        // GET: /ClassRoomSceduleAllocation/
        private DepartmentManager departmentManager;
        private AllocateClassRoomManager allocateClassRoomManager;

        public ClassRoomSceduleAllocationController()
        {
            departmentManager = new DepartmentManager();
            allocateClassRoomManager = new AllocateClassRoomManager();
        }

        [HttpGet]
        public ActionResult ClassRoomScedule()
        {
            ViewBag.Departments = departmentManager.GetDepartmentForDropdown();
            return View();
        }
        public JsonResult GetClassRoomSceduleByDepartmentId(int deptId)
        {
            List<ClassRoomScedule> classRoomScedules = allocateClassRoomManager.GetClassRoomSceduleByDepartmentId(deptId);
            return Json(classRoomScedules);
        }
	}
}

UniversityManagementWebApp/UniversityManagementWebApp/Views/ClassRoomSceduleAllocation/ClassRoomScedule.cshtml
@model UniversityManagementWebApp.Models.Department
@{
    ViewBag.Title = "ClassRoomScedule";
    Layout = "../Shared/view1.cshtml";
}

@section style
{
    <style>
        th, td {
            border: 1px solid black;
        }
    </style>
}
<body>
    @using (Html.BeginForm())
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(x => x.Name)
                </td>
                <td>
                    @Html.DropDownList("DepartmentId", new SelectList(ViewBag.Departments, "Value", "Text"))
                </td>
            </tr>
        </table>
        <table>
            <thead>
                <tr>
                    <td>Course Code</td>
                    <td>Name</td>
                    <td>Schedule Info</td>
                </tr>
            </thead>
            <tbody id="sceduleDetails"></tbody>
        </table>
    }


    @section scripts
    {
        <script src="~/Scripts/jquery-3.5.1.min.js"></script>
        <script>

            $(document).ready(function () {

                $("#DepartmentId").change(function () {

                    var departmentId = $("#DepartmentId").val();


                    var json = { deptId: departmentId };


                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetClassRoomSceduleByDepartmentId", "ClassRoomSceduleAllocation")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $("#sceduleDetails").empty();


                            $.each(data, function (key, value) {

                                $("#sceduleDetails").append('<tr><td>' + value.CourseCode + '</td> <td>' + value.CourseName + '</td>  <td>' + value.ClassScheduleInfo + '</td> </tr>');

                            });

                        }
                    });

                });
            });
        </script>
    }
</body>